### ISSUE TITLE
stable_sid vs NameIdentifier

### ISSUE THREAD

**Issue by danielloczi** [Azure/azure-mobile-apps-net-server#108]
Hi,

I migrated our Mobile App server code from v0.1.508 to v1.0.119.0 and later to v1.1.157.1. The service is configured to use Microsoft, Google,Twitter and Facebook identity providers with token store.
After the migration I experienced weird things when tried to get User SID. Originally I used the value of the NameIdentifier claim, but for some reason it returned a different value than the UserID that I saw on the client side, but realised that there was a Claim key: stable_sid which was okay. So I started to use stable_sid instead of NameIdentifier. It was ~1 month ago. 

When I wrote some tests in the last couple of days I experienced different IDs on the client and server side again. After some investigation it turned out, that I should use NameIdentifier (again..?).
Btw all of the articles and docs that I found are talking about NameIdentifier, so I think that is the one, that I need indeed. 

Could you confirm that if I need an ID for the user that will not change and consistent, then the claim, which key is the NameIdentifier is a good choice?

I also would like to know, that what is stable_sid, what is the relation between stable_sid and NameIdentifier?

Thank you in advance!

**Comment by brettsam** [comment]
There's a number of things at play here -- I'll turn this post into a wiki page shortly so that I can point people there in the future.

**sid vs stable_sid**
When App Service Authentication was first released, the sid was generated based on the email of the user. This made it great for linking a user across two providers if they used the same email for google, facebook and twitter, but it meant that the sid was not stable. Someone could change their registered facebook email and suddenly the sid would be different. This is why [the Understanding User Ids](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids) wiki page was written -- to show how you could generate your own stable user ids.

A subsequent update was pushed out that keeps the sid generation the same but adds a new claim called stable_sid that is generated based on the identity given to us by the provider. This is guaranteed to be stable for that user on that provider, but it is not stable across providers. So the same email address used at twitter, google, and facebook will all have different stable_sid values. But if someone changes their facebook email address, they will continue to have the same facebook provider id, and thus the stable_sid will remain stable. This does mean that applications will have to do some work to manage users if they want to allow registering with multiple providers and having them resolve to the same user in your system.

**Moving to stable_sid**
The plan is that stable_sid will be the default sid for all newly-created applications. In order to prevent breaking existing apps, the old sid behavior has to stay around in some form. This is why you see both the sid and the stable_sid in your claims. You can enable stable_sid to become the default sid (which is recommended) by setting an App Setting of `WEBSITE_AUTH_HIDE_DEPRECATED_SID` to `true` in the portal.

**Client ids**
At one point, there was also a bug introduced that sends the wrong sid back to the client in some scenarios. This should always match the sid on the server (not stable_sid) but in this case they were getting switched. This fix should now be released so please let me know if you are seeing a different user id on the client that does not match your sid value on the server. If you move to using stable_sid, you will then only have one sid value (the stable one) and your client should match this.

Let me know if this helps explain it at all -- I'll be translating this into a wiki topic soon and will link back here when that's done.

And here's a related issue with some more links and context: https://github.com/Azure/azure-mobile-services/issues/883

**Comment by danielloczi** [comment]
Thank you for the good explanation! It's a good idea to put this to the [existing Wikipedia article](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids)!.
I decided to switch to the new - stable_sid based - method.

One thing that was not clear based on your reply, but I tried it: if the `WEBSITE_AUTH_HIDE_DEPRECATED_SID` is set to `true`, then the stable_sid disappears from the claims, but its value will be assigned to the NameIdentity claim (and of course it also reflects the ID, that will be showed on the client side). So after the switch I still have to use the NameIdentity key on the server side.

If you don't mind I have another question about the stable_sid:
You mentioned, that stable_sid is generated based on the id, that was presented by the identity provider. In that case, I guess the stable_sid should be the same even if I login from totally different Mobile App Service instances. Is it true?

Let me tell you an example: if I create a Mobile App Service instance (and the corresponding FB/G+/TW/Ms identity provider apps) in the EU-North datacenter and another Mobile App Service instance (and its own FB/G+/TW/MS identity provider apps) in the EU-West datacenter, then it will not matter which Mobile App Service will the Mobile Application connect to, the user will get exactly the same stable_sid. I would like to use this multi-instance config for redundancy purposes. Will it work?

Thx!

**Comment by lrz-hal** [comment]
Which is the right way to get stable_sid. 

`var user = this.User as ClaimsPrincipal;
var stableSid = user.FindFirst(ClaimTypes.NameIdentifier).Value;`

Has stable_sid the same value for multiple providers which has the same email?

Thanks

 Martin

**Comment by danielloczi** [comment]
I think your code the get the stable_sid, is okay, just don't forget to hide depracated sid in the application config - other case you will get the 'old school' sid.

The stable_sid will be different if a user logs in with different providers which have the same email.

**Comment by lrz-hal** [comment]
Ok. Thanks for the explanation.


Von Outlook gesendet






On Sun, Apr 10, 2016 at 9:32 AM -0700, "danielloczi" <notifications@github.com> wrote:





I think your code the get the stable_sid, is okay, just don't forget to hide depracated sid in the application config - other case you will get the 'old school' sid.

The stable_sid will be different if a user logs in with different providers which have the same email.


---

**Comment by brettsam** [comment]
Note -- I've finally updated https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids with details from this thread.
