### ISSUE TITLE
Not possible to upgrade existing Mobile Service to the new App Service when using Microsoft Live authentication and storing user IDs in the database

### ISSUE THREAD

**Issue by pglazkov** [Azure/azure-mobile-apps-net-server#112]
Hi,

I have a mobile service that uses Microsoft Live authentication (as described [here](https://azure.microsoft.com/en-us/documentation/articles/mobile-services-how-to-register-microsoft-authentication/)). I also store user IDs in the database to associate data to the users (user IDs are in the format MicrosoftAccount:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx). Now I want to upgrade the mobile service to the new app service SDK as described [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/). But it seems that I cannot do it without breaking the application for the current users.

The [article](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/) says that:

> If your app does take any dependencies on user IDs, it is important that you leverage the same registration with an identity provider if possible. User IDs are typically scoped to the application registration that was used, so introducing a new registration could create problems with matching users to their data.

This means that I have to use the same Microsoft Live app registration that has a redirect URL pointing to my mobile service (https://myapp.azure-mobile.net/login/microsoftaccount).

On the other hand, the [article](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/) says that in order to upgrade I need to create a new duplicate app service instead of updating the existing one:

> The Mobile Services client SDKs are not compatible with the new Mobile Apps server SDK. In order to provide continuity of service for your app, you should not publish changes to a site currently serving published clients. Instead, you should create a new mobile app that serves as a duplicate.

But, I cannot do that because this duplicate app service would have a different URL that I would need to specify as a redirect URL in my Microsoft Live app registration, which I cannot change as this would break the old mobile service and old clients.

So, if I understand everything correctly, it is impossible to have two different app services (current and the new) to use the same registration with the identity provider because the identity provider has a reference back to the service in the form of the redirect URL. And if I create a new registration with the identity provider for the new app service, the user IDs would be different and and users would not see their data. Seems like a chicken and egg problem.

Is there any way I can upgrade my app without breaking the app for the users who still use the old version of the app?

Thanks.
Kind regards,
Pavlo

**Comment by adrianhall** [comment]
Hey Pavlo,

You bring up some excellent points.  I'd like to discuss internally and test a few things out before suggesting something on this forum.  Please bear with us.

**Comment by adrianhall** [comment]
Hey @pglazkov 

Can you please let us know your client SDK and server SDK preferences?  We feel that switching to the client flow will fix the problem, but we want to do a PoC to ensure we are doing the right thing for your situation.

**Comment by pglazkov** [comment]
Hi @adrianhall,

Here are the SDK NuGet packages that I use: 

- Client: WindowsAzure.MobileServices (version 1.3.2)
- Server: WindowsAzure.MobileServices.Backend (version 1.0.470)

Actually, the full source code of my app is [here ](https://github.com/pglazkov/Linqua/tree/uwp10) on GitHub, so you are free to check it out and see how exactly it is implemented. And there is a WP 8.1 version of the [app in the app store](https://www.microsoft.com/en-us/store/apps/linqua/9wzdncrcvrjs). 

I'm not sure what exactly you mean by "client flow", but I think this is exactly how it works right now. I use Live Connect API to authenticate users on the client ([code](https://github.com/pglazkov/Linqua/blob/uwp10/Linqua.PT/SecurityManager.cs#L116)), so that they don't have to log in to my app if they are already logged in on their Windows Phone device. And I want to keep it working this way, but it seems that I cannot upgrade to the new SDK without breaking the existing app that is in the store, as I described in my original question.

Kind regards,
Pavlo

**Comment by mattchenderson** [comment]
Hi @pglazkov - If you are already using the Live SDK, then you actually should be good to go. You can configure App Service Authentication / Authorization with the same ID and secret pair, and it should accept the tokens, with your users having the same IDs as before.

The issue is really if you are just using the raw `LoginAsync("microsoftaccount")` method, which you are not.

On the server, you will still need to make sure you grab the old style ID. I do that with the following:
`            MicrosoftAccountCredentials creds = await this.User.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(this.Request);`
`            string mobileServicesUserId = creds.Provider + ":" + creds.Claims[ClaimTypes.NameIdentifier];`

GetAppServiceIdentityAsync() is an extension method, so make sure you have `using System.Security.Principal;`

In looking at your login code, I think everything should pretty much be the same. I did notice you are using an AuthenticationToken instead of an AccessToken, and that could cause an issue. These days I tend to write Live SDK (v5.6) code for getting AccessTokens with the following:
`LiveAuthClient authClient = new LiveAuthClient();`
`                    LiveLoginResult loginResult = await authClient.InitializeAsync(scopes);`
`                    loginResult = await authClient.LoginAsync(scopes);`
`                    string token = loginResult.Session.AccessToken;`
`                    JObject payload = new JObject();`
`                    payload["access_token"] = token;`
`                    user = await App.MobileService.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, payload);`

That does require you to have a store association with the ID and secret, but I think your setup already should have that. If not, you can move your store association to your current client ID. In the application registration portal, find the app that has the Windows Store association. At the bottom of the WIndows Store details, there's a "Link to a different app" button that will allow you to move it to the client ID you're already using.

For anyone else who may stumble upon this, associating the app with the store and making that remapping is the key step needed to move from server flow to client flow. Then the code I've shown above should allow you to log in just fine, with all users having the same IDs.

**Comment by mattchenderson** [comment]
Also worth mentioning, the [OneDrive SDK](https://dev.onedrive.com/sdks.htm) is recommended over the Live SDK these days and might be worth considering (certainly not necessary). The code on the client can be really clean though (and you get the package through NuGet instead of a direct reference).

`IOneDriveClient oneDriveClient = OneDriveClientExtensions.GetUniversalClient(new string[] { "wl.signin" });`
`AccountSession session = await oneDriveClient.AuthenticateAsync();`
`JObject payload = new JObject();`
`payload["access_token"] = session.AccessToken;`
`user = await App.MobileService.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, payload);`

**Comment by pglazkov** [comment]
Hi @mattchenderson,

Thank you for the detailed info. However, I still could not make this work. Here is what I did:

- Created a new App Service via the Azure Portal for the upgraded version of the backend service. 
- Upgraded the SDK and made the required code changes following [this article](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services). 
- Configured App Service Authentication / Authorization with the same ID and secret pair as my existing azure mobile service (taken from the existing registration with Microsoft Live). 
- Upgraded the client app to use the new version of the client SDK.
- Changed the [authentication code](https://github.com/pglazkov/Linqua/blob/app-service-upgrade/Linqua.Lib.UWP/SecurityManager.cs#L128) to use OneDrive SDK using the code snipped that you provided.

Now, when I run the app and try to authenticate the user, the following line fails with an exception:

`user = await App.MobileService.LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, payload);`

The exception was:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
```   
You can see the source code of my upgraded app service and the client app in the [app-service-upgrade](https://github.com/pglazkov/Linqua/tree/app-service-upgrade) branch here: https://github.com/pglazkov/Linqua/tree/app-service-upgrade. The new app service is deployed to Azure at https://linqua-v2.azurewebsites.net/ (the [source code](https://github.com/pglazkov/Linqua/tree/app-service-upgrade/Linqua.Service)).

Besides, I still don't quite understand how this could work in principle, because Windows Live registration requires the redirect URL (as described [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-how-to-configure-microsoft-authentication/)), but now I have two app services (the old one serving existing clients and the upgraded one) deployed at different URLs (http://linqua.azure-mobile.net and http://linqua-v2.azurewebsites.net respectively). So, unless you're saying that the redirect URL is not important in this case and can be set to anything, I cannot have two versions of the app service running simultaneously leveraging one Windows Live registration.  Basically the chicken and egg problem I described in my original question.

**Comment by pglazkov** [comment]
Hi @mattchenderson,

After starting the upgrade procedure from scratch and following the upgrade [walkthrough](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/) once again I was finally able to make the authentication work using the "access token" approach as you suggested ([code](https://github.com/pglazkov/Linqua/blob/app-service-upgrade-2/Linqua.Lib.UWP/SecurityManager.cs#L118)). However, now I have a different problem - I cannot get the same user IDs as I had before. I used the code that you provided:

```
MicrosoftAccountCredentials creds = await this.User.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(this.Request);
string mobileServicesUserId = creds.Provider + ":" + creds.UserClaims.Single(x => x.Type == ClaimTypes.NameIdentifier).Value;
```
The `NameIdentifier` claim returns a different (shorter) ID, e.g. "acf8bfd4384116ce" instead of "abd27add722a90a94c192bd63c30731d" that I have stored in the database to identify the user's data. 

I suspect this is because I used to authenticate users with "authentication token" and now I switched to "access token". You also mentioned that using "authentication token" could cause an issue: 

> I did notice you are using an AuthenticationToken instead of an AccessToken, and that could cause an issue.

Could you please elaborate on this a bit more? 

Is there still a way to get the old style user IDs when authenticating users with the "access token" approach?

**Comment by pglazkov** [comment]
Looks like the user ID that I need is available on the client side via `AccountSession.UserId` (when using OneDrive SDK approach) or via `OnlineIdAuthenticator.AuthenticatedSafeCustomerId`(when using [OnlineIdAuthenticator approach](https://github.com/pglazkov/Linqua/blob/app-service-upgrade-2/Linqua.Lib.UWP/SecurityManager.cs#L118)). 

According to the [documentation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.security.authentication.onlineid.useridentity.safecustomerid), those are **application specific** IDs, whereas, according to my understanding, the value of the NameIdentifier claim on the azure app service side is an ID of the user specific to the MicrosoftAccount provider, but not specific to the application. 

The question is, how can I get that application specific user ID in my app service controller? Previously, with the old version of Azure Mobile Services SDK, that user ID was available via [ServiceUser.Id](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.mobile.service.security.serviceuser.id.aspx) property and that is what I store in the database to associate data to the users.

**Comment by adrianhall** [comment]
All the claims being returned by the provider are stored in the /.auth/me endpoint and available via the GetAppServiceIdentityAsync<> method.  You may need to dig a little to see which Id is actually required.
