### ISSUE TITLE
Request to refresh token returns forbidden after logout and login

### ISSUE THREAD

**Issue by CendaL** [Azure/azure-mobile-apps-net-server#126]
I use .NET backend with JS client and this behavior looks like a bug to me:

1) User logs in via google provider:

```
var loginOptions = {
    parameters: {
        access_type: 'offline'
    }
};
client.loginWithOptions('google', loginOptions).done(...);
```

2) Calls to refresh token succeed:

```
client._request('GET', '/.auth/refresh', function (error, response) {...});
```

3) User logs out:

```
client.logout();
```

4) User logs in again the same way as in step 1.

5) Calls to refresh token fails with HTTP status code `403 (Forbidden)`

Why am I getting forbidden? When I remove access to the app on Google's portal and log in, it works again until I logout/login.

**Comment by brettsam** [comment]
It looks like this is a bug in how we handle Google's login flows with refresh tokens. Only the first login attempt returns a refresh token (which we store). Subsequent logins do not include the refresh token (even though it is requested -- you only get one at a time), so we remove the stored refresh token. Then the next time you attempt to refresh, we don't find a refresh token, and it fails with a 403. You should be able to remove step 3 from your repro above and see the same thing.

We'll work on a fix and close this issue when it's deployed.

There is a workaround -- in your loginOptions, also send `prompt: 'consent'`. This will cause all login attempts to re-authorize the user and Google will always return the refresh token. When the fix is deployed, you shouldn't need this anymore.

Let me know if that works for you.

**Comment by CendaL** [comment]
I confirm all you wrote - step 3 is not needed, it's enough to login again.
And the workaround also works although user has to always approve _Have offline access_ during the login

**Comment by adrianhall** [comment]
@CendaL doing some clean-up.  I believe the fix for refresh was deployed.  Can you verify and close if so?

**Comment by CendaL** [comment]
@adrianhall I'm sorry but I have abandoned my app recently so it is not easy for me to test it anymore. Feel free to close it if you think it is fixed.

**Comment by PeterKolstad** [comment]
Hi
I have the same issue but only on xamarin.ios and not for xamarin.Android. The codes look exactly the same so is should work but fore some strange reason it doesnt work on ios.

**Comment by adrianhall** [comment]
If it works in Android and now iOS, then it is not a server issue, but a client issue.  Please open a fresh issue with full details on the appropriate client repo - that's Azure/azure-mobile-apps-net-client for Xamarin issues.

**Comment by PeterKolstad** [comment]
Thanks for your quick reply! Are you sure about that it has to be a client issue be course I get the exact same respons: "Refresh failed with a 403 Forbidden error. The refresh token was revoked or expired"

**Comment by adrianhall** [comment]
If you are getting "The refresh token was revoked or expired" - the likelihood is that it expired or never got fetched.    It's not an issue with the SDK - it's just telling you what has happened to the token.  We don't mess with the token on the way through, so it's what the auth provider is telling you.

If you were getting an error on iOS and not Android with the same code, then it's generally an issue with your code when you are in .NET.  The code to handle refresh tokens is the same codepath.

**Comment by longnt-ttm** [comment]
Recently I have the same issue.
After capture the server response and looking for refresh token I notice the following detail:

- With Google account that have 2 steps authentication enabled, the refresh token is empty.
- With Google account that only use normal authentication (user/password), refresh token is returned.

P/S: I was using azure-mobile-apps-net-client but it may have the same issue here.
