### ISSUE TITLE
LoginAsync with AAD Auth Error

### ISSUE THREAD

**Issue by tylerd** [Azure/azure-mobile-apps-net-server#172]
I have configured the solution to use AAD with the .NET backend exactly how this article outlines.
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-how-to-configure-active-directory-authentication
Completed: _(Optional) Configure a native client application_

However I am getting this error when calling client.LoginAsync
`You do not have permission to view this directory or page.`
Request:
`{Method: POST, RequestUri: 'https://tylermobile.azurewebsites.net/.auth/login/aad', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  X-ZUMO-INSTALLATION-ID: 43cb9832-4096-4351-a7ea-ea31a5444d49
  Accept: application/json
  User-Agent: ZUMO/3.0
  User-Agent: (lang=Managed; os=Windows; os_version=6.2.0.9200; arch=Win32NT; version=3.0.41013.0)
  X-ZUMO-VERSION: ZUMO/3.0 (lang=Managed; os=Windows; os_version=6.2.0.9200; arch=Win32NT; version=3.0.41013.0)
  Content-Type: application/json; charset=utf-8
  Content-Length: 1514
}}`

I can validate with a browser using the same URL but it does not work with a client app.

**Comment by adrianhall** [comment]
Firstly, this is a CLIENT issue, not a SERVER issue.  The server doesn't do any authentication - the /.auth endpoints are all within App Service, not your server code.

Secondly, we need to see code here.  There are two pieces - firstly, you need to use ADAL to get the client side authentication done.  This returns an authentication Token.  Once you have this, you call LoginAsync("aad", JToken) with the JToken set up appropriately.   In order to reproduce, we need to see the code that you are using and to understand how you have configured the AAD and the App Service Authentication / Authorization.

Please file this bug in the Azure/azure-mobile-apps-net-client repo - close this one when done.  (I'd move it myself but we can't move issues between repos)

**Comment by tylerd** [comment]
After doing some digging, it looks like App Service configuration is the cause for this issue.

Apparently the very generic error message of `You do not have permission to view this directory or page` occurs when you are using a token with an audience which is not included in the Allowed Token Audiences setting on the App Service.
