### ISSUE TITLE
Support for AspNetCore

### ISSUE THREAD

**Issue by dansiegel** [Azure/azure-mobile-apps-net-server#210]
AspNetCore and EntityFrameworkCore are both released and "stable". This really needs to be updated to support these newer technologies.

**Comment by dansiegel** [comment]
Any update on this? I believe the last thing the Mobile Apps Server needed in .NET Standard was the OData components, which it looks like have been out since the beginning of May in Version 7.2.0

**Comment by andreujuanc** [comment]
I need to start a project next week, I just want to know if I can help on this, since I already have another app using the node version, runs fine, but performance could be an issue in this new project. 

I have the chance of using something from scratch and help testing and improving it.

Just need to know if this "feature" gonna happen, or if I should just do my own server implementation. I really don't want to start something and then notice Net Core support for this library came after.

There is lots of support for this feature all around, personally I think it's the way to go.

Cheers!

**Comment by dallancarr** [comment]
Any update on this?

**Comment by Silthus** [comment]
Is this project still maintained and alive? Seems pretty dead to me...

**Comment by nor0x** [comment]
any official updates from MS on this topic? Really frustrating to see the cool features of .netcore and not being able to use it 😩

**Comment by lsuarez5280** [comment]
This is likely to remain blocked until the OData team completes the outstanding feature branch for Core support (which is still moving along slowly, tracked at https://github.com/OData/WebApi/issues/939). The server Tables library has a dependency on this for moving to WebApi on Core.

**Comment by elamalani** [comment]
Hey everyone,

Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-server#future-of-azure-mobile-apps). At this point, we ar4e not adding any new features to the product.

**Comment by mzhukovs** [comment]
sorry, just so it's 100% clear - Microsoft won't be updating the C# backend option for Azure Mobile Apps to be .NET Core + EF Core? Please confirm when you get a chance, thanks! @elamalani

**Comment by elamalani** [comment]
@mzhukovs You are correct - unfortunately, we are not adding new features in Azure Mobile Apps.
