### ISSUE TITLE
UpdateAsync try to re-add nested object

### ISSUE THREAD

**Issue by ghost** [Azure/azure-mobile-apps-net-server#219]
I have a data model that consists of appointments, and patients. Every appointment has a patient property. When I make a change to an appointment and then call UpdateAsync, I get the following error:

The operation failed due to a conflict: 'Violation of PRIMARY KEY ...' . Cannot insert duplicate key in object

It's pretty clear that azure is trying to re-add the patient to the patients table whenever I modify the appointment. Why? How do I avoid this?

**Comment by oatsoda** [comment]
I suspect you are trying to use relationships with your Entities.

See [this answer](https://stackoverflow.com/a/40701134/868159):

> Azure Mobile Apps does not support relationships

I would suggest you try changing your EF models so that they don't load child relationships automatically (e.g. remove the "virtual" from the Patient property).  

Alternatively, if you need the children loaded up, you can just make sure they don't get serialised across  the wire [by changing the JSON formatting options](https://github.com/Azure/azure-mobile-apps-net-server/issues/218#issuecomment-315721255)
