### ISSUE TITLE
How to exclude properties from Json returned using TableController

### ISSUE THREAD

**Issue by antitheos** [Azure/azure-mobile-apps-net-server#228]
I may be missing something, but my searches have not found anything.
I have an entity as defined below, returned from from .Net backend Mobile App

```C#
public class Example : EntityData{
    public string ExampleName { get; set; }
    [JsonIgnore]   
    public string ExampleIgnore { get; set; }
}
```

When this is returned from a TableController the field ExampleIgnore is included in the JSON payload, when I expected it to be excluded.
Is there another attribute or mechanism for ignoring properties and removing them from the JSON payload?
I assumed JsonIgnoreAttribute would do the trick, am I incorrect?

I am using v2.0.0.0 of the sdk

**Comment by prebenh** [comment]
I think the problem starts here: 
https://github.com/Azure/azure-mobile-apps-net-server/blob/04d75cadc137cc478f98edfa1fa5b868e5548dfd/src/Microsoft.Azure.Mobile.Server.Tables/Serialization/TableContractResolver.cs#L79 

Because of the properties are cleared an then re added, the attributes are not taken into account.

**Comment by antitheos** [comment]
@prebenh thanx.  
I had to create a second class with just the properties I need to get around this issue.

**Comment by elamalani** [comment]
I'll close this issue since the problem seems to be fixed.

**Comment by prebenh** [comment]
It's a work around. But maybe the TableContractResolver should take into account Json Attributes that are specified
