### ISSUE TITLE
JWTSecurityToken with no expiry causes 401 Unauthorized errors

### ISSUE THREAD

**Issue by leedjones** [Azure/azure-mobile-apps-net-server#234]
I recently ran into a problem whereby my users could sign in to my mobile app or register a new user and the security token would be issued fine:

AppServiceLoginHandler.CreateToken(claims, signingKey, audience, issuer, null);

whereby the expiry is set to null for no expiry.
However, subsequent requests which are to controllers decorated with the [Authorize] attribute fail with a 401 Unauthorized response.
After much digging and some help by [Bruce Chen on StackOverflow](https://stackoverflow.com/questions/46586383/401-unauthorized-when-making-request-to-azure-mobile-service/46598530#46598530) he discovered that setting the expiry to null is the cause of the problem. If you change this to a finite period, eg:

AppServiceLoginHandler.CreateToken(claims, signingKey, audience, issuer, TimeSpan.FromDays(90));

Then the same request to the mobile serive authenticates and works fine.

Note, this only happens when deployed to Azure. If I run and debug it locally, it works fine with null expiry.

**Comment by elamalani** [comment]
@leedjones Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). This issue was opened a few months back, I'll close this issue for now but let us know if you have any questions. Thanks!
