### ISSUE TITLE
Azure Offline Sync Updated At pulls whole data during the Incremental Sync

### ISSUE THREAD

**Issue by thabotharshan** [Azure/azure-mobile-apps-net-server#241]
I have a table controller, which has one way sync (Only get since there is no any update from mobile). So the very first time when I do the Pull Async it has pulled whole data since my Update At filed has the same timestamp for all the records. Now Second time I just wanted to do the incremental Pull (Note I do pass a name value to Pull Aync to enable incremental sync). 

But the problem is, it retrieves whole data again since there is no updated time stamp in Updated At (Because there is no update method in the Table Controller since it is one-way sync-Azure to mobile). How can I omit pulling data again if there is no update while all the Update At values are same time stamp? The issue is same as mentioned in below link. Do we still need to do one record update in order to fix this?

https://social.msdn.microsoft.com/Forums/office/en-US/ff002e85-1313-449f-89eb-cd45c1a4846c/mobile-services-sync-pullasync-and-updatedat?forum=azuremobile

Thanks in Advance

**Comment by MatkovIvan** [comment]
Hi @thabotharshan 

Thanks for getting in touch!
As mentioned in the link, this is by design.
Incremental sync feature store latest `updatedAt` value and then add the filter to select only entities with `updatedAt` value **greater or equal** than you already have on the device.

So, to make it correctly you can:
1. Avoid using the same `updatedAt` values as mentioned in the [doc](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync#how-sync-works):
    > To use incremental sync, your server must return meaningful `updatedAt` values
2. Add some custom filter to query after the initial sync. Of course, if you can identify the hallmark of initial entries.

Best,
Ivan

**Comment by hashmurali** [comment]
Did anyone manage to resolve the issue?
