### ISSUE TITLE
GetAppServiceIdentityAsync() throws exception after last update

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-server#277]
The authentication has been broken after the last azure mobile app update (1.1.2). I cannot get user claims from the ClaimsPrincipal or from GetAppServiceIdentityAsync() method with the setting property runtimeVersion: "1.0.0" or removing it. In both cases the ClaimsPrincipal returns only basic claims, and not the expected claims for AAD authentication:

[basic claims when failing.txt](https://github.com/Azure/azure-mobile-apps-net-server/files/3116273/basic.claims.when.failing.txt)
[expected claims when working fine.txt](https://github.com/Azure/azure-mobile-apps-net-server/files/3116274/expected.claims.when.working.fine.txt)

The GetAppServiceIdentityAsync() method, which is supposed to be the prefered way to get the user claims, throws different exceptions depending on the runtimeVersion configuration. When I remove it or set it to "1.0.0" it throws a HttpRequestException:

[exception.txt](https://github.com/Azure/azure-mobile-apps-net-server/files/3116285/exception.txt)

When I set runtimeVersion to "1.0.3" it throws an InvalidOperationException:

[exception2.txt](https://github.com/Azure/azure-mobile-apps-net-server/files/3116289/exception2.txt)

But with runtimeVersion "1.0.3" at least I can get the claims from the ClaimsPrincipal object.

I've tried also with runtimeVersion "1.1.2" but I get the same behavior as with runtimeVersion "1.0.0".

Summary table

runtimeVersion | ClaimsPrincipal | GetAppServiceIdentityAsync()
-- | -- | --
not present | basic   claims | HttpRequestException
1.0.0 | basic   claims | HttpRequestException
1.0.3 | expected   claims | InvalidOperationException
1.0.7 | expected   claims | InvalidOperationException
1.1.2 | basic   claims | HttpRequestException

**Comment by ConnorMcMahon** [comment]
So was able to reproduce the HttpRequestException found in version 1.1.2, and this is likely not a regression. It is just the InvalidOperationException present in 1.0.3 and 1.0.7 was occuring in the code before the HttpRequestException is now being hit, so now that the InvalidOperationException is not being hit, we are seeing the HttpRequestException.

Starting [early last year](https://github.com/Azure/app-service-announcements/issues/104), our product started enforcing inbound requests to use TLS 1.2 unless various conditions are met. It turns out that earlier versions of .NET (I believe 4.6.1 and earlier?) default outbound requests to TLS 1.0. Since `GetAppServiceIdentity()` calls the site's own `/.auth/me?provider={provider}` endpoint to get the user claims, the request throws an `HttpRequestException`, as the site refuses to acknowledge a request using TLS 1.0.

Essentially, to make this behavior work, your app needs to start using TLS 1.2. I achieved this by adding the below line to my Startup.cs file, though I believe you can add it almost anywhere in the pipeline.

`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`. 

This made the HttpRequestException go away for me, and hopefully does for you as well.

**Comment by asierpn** [comment]
@ConnorMcMahon the TLS 1.2 tweak has solved the issue. I've removed the runtimeVersion setting from our authentication config as I understand it is the best option.
