### ISSUE TITLE
ProviderCredentials.UserId does not return the same value that the MobileAppUser.UserId did

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#33]
MobileAppUser is gone (understood) and the replacement to get UserId, ProviderCredentials, returns an email address rather than the original UserId that the MobileAppuser did. This is with Microsoft.Azure.Mobile.Server.Authentication.0.3.36.0. This also affects the Mobile App UserId because it is still returning a "sid:value" which is now the same for users of different providers that have the same email address specified on each provider.

**Comment by renzska** [comment]
Is it possible for UserId to return the claim: nameidentifier, so we can grab the unique provider assigned id from UserId? If not, can we get a better understanding of how UserId is created and whether it will stay the same between versions (it has been changing from "Provider:someid" to "sid:somedifferentid" now to "email".

**Comment by renzska** [comment]
I've found that calling the following:

ClaimsPrincipal user = this.User as ClaimsPrincipal;
            var userId = user.GetUserId();

returns the same UserId as the MobileAppUser used to: "sid:guid".

where the GetUserId extension method is as follows:

public static string GetUserId(this ClaimsPrincipal principal)
        {
            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }
            return principal.FindFirstValue(ClaimTypes.NameIdentifier);
        }

 public static string FindFirstValue(this ClaimsPrincipal principal, string claimType)
        {
            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }
            var claim = principal.FindFirst(claimType);
            return claim != null ? claim.Value : null;
        }

**Comment by renzska** [comment]
To clarify:

//
ClaimsPrincipal user = this.User as ClaimsPrincipal;
GetNameIdentifierClaim();
 //NameIdentifier Claim returns the "sid:guid" 

//
ProviderCredentials identity = await user.GetAppServiceIdentityAsync<GoogleCredentials>(request);
identity.UserId = "user email address"

//
MobileService.CurrentUser.UserId // returns the same "sid:guid" as the ClaimsPrincipal method

//
both the 1st and 2nd UserId values are the same for a Google Account and Facebook Account that have the same primary email address

**Comment by brettsam** [comment]
In your last example, 1 and 2 are called on the server and 3 is called on the client, correct?

Yes, this has changed with the move to using the new App Service Authentication.

The NameIdentifier claim (sid:identifier) is a unique id that App Service Authentication creates that will identify this user for your application. As you've seen, each of these ids can map to one or more ProviderCredentials that has provider-specific data that you can get via GetAppServiceIdentityAsync. 

The ProviderCredentials.UserId value depends on the provider, but it tries to use the email registered with the provider so it can automatically link the provider creds with a single sid on your service.

So if you want to identify a user within your app, using the 'sid:identifier' id is the way to do it.

We'll have some deeper docs coming out on this in the future, but let me know if you have any other immediate questions that I can help answer.

**Comment by renzska** [comment]
You are correct about the server and client question.

It was intentional then that a user who logs into my app using their Facebook and then their Google account, when the ProviderCredentials.UserId from both services is their email address and they match, will have the same "sid:identifier"?

It sounds like I should still store the unique provider user id as I've seen the "sid:identifier" change between versions and services. Storing it with the sid:identifier at least gives me a way to map up users if the "sid:identifier" ever changes in the future.

Also, what happens if the email address from one of the services changes? Does their "sid:identifier" now change?

On a side, but related note, in an ASP.NET 5 RC1 Web Application with the same service auth ClientID/AppID and ClientSecret/ClientID as my mobile app, the HttpContext.User.GetUserId() functionality returns a completely different id. Is there anyway to match these with my previous examples 1 and 3?

When creating a Mobile App, Azure SQL Backend, and an ASP.NET Web Application accessing the same data, and the UserId information doesn't match, it makes it so I need to resort to using the Provider Specific User ID for matching up records in the DB.

Is there a different recommended approach for doing a Mobile App/ASP.NET Web App/Single Azure SQL Backend for an application while getting all of the specific functionality per mobile and web?

Thanks for taking the time on this,

John

**Comment by PaulAchess** [comment]
I use `User.Identity.GetUserId();` from the `IdentityExtensions` of `Microsoft.AspNet.Identity.Core`. 

No cast needed, works like a charm even with my custom auth. But I admit it's kind of weird to have the email address in ProviderCredentials' UserId.

**Comment by brettsam** [comment]
Let me backtrack on what I said above (sorry!) -- as you mentioned, the registered email of a user with a provider may change, which means the generated 'sid:identifier' for that user would change. For example, I logged in with Facebook, looked at my sid, changed my primary email, and verified that my sid was now different.

The sid is unique to App Service Authentication and is used internally as an id to store the other claims from the provider in a token store. GetAppServiceIdentityAsync() pulls those claims from the token store and turns them into a ProviderCredentials object.

That being said, the best id to use to uniquely identify a user, is to use the provider's unique id (I misspoke when I said to use the sid above). Even if the email changes, the unique id will not. For Mobile Apps, that is available via the ClaimTypes.NameIdentifier claim from the ProviderCredentials.Claims array.

You're right that it does feel odd that we're surfacing the email now as the user id, when that may change. I'll see if we can address that.

As for how other backends surface their user ids, I'll have to investigate that. If the other backend is not using App Service Authentication, then what they surface as the user id will be different. However, any authentication using the same provider client id should contain that provider's unique id somewhere in their claims. I've not set this up in ASP.NET 5 yet -- what value does it return as the user id? Do you get the provider's unique id also?

**Comment by renzska** [comment]
@brettsam Thanks for looking into this further.

What you've stated sounds accurate to what I've seen from my tests. On the ASP.NET 5 side of things, it looks like the NameIdentifier claim returns the guid that is created in the database that it creates, however, I haven't had much time for testing to see if it's possible to find the provider unique id in those claims. I'll do some testing and report back if it's available.

Currently, it sounds like using the Provider Unique Id is the way to go. It adds a little bit of code to each call on the server side to make sure that we only return the records for that user, but it's doable. At least I shouldn't have to worry about losing the user info as long as that Provider Unique Id does not change.

On the Facebook side of things, the user id is per app, but they do have a means of using the business api to get the unique ids for a user to your apps, so you can "translate" between the ids based on the apps if using the same backend database between those apps.

**Comment by renzska** [comment]
@brettsam 

In the ASP.NET 5 application I am able to get the Unique Provider Id using the following code:

'var info = await _signInManager.GetExternalLoginInfoAsync();
var uniqueProviderId = info.ExternalPrincipal.FindFirstValue(ClaimTypes.NameIdentifier);'

**Comment by danbridgellc** [comment]
I recently migrated to Azure Mobile App from AMS - I am using custom authentication as well as Providers...I have Providers working fine but the custom auth is failing to work correctly.  I have verified that it generates a token via the AppServiceLoginHandler.CreateToken successfully and the token is in the client request X-ZUMO-AUTH header, however, the requests are failing with 401 unauthorized.  I have verified that my signingKey has what appears to be a valid value...I am convinced that something is wrong with the custom token since the providers are working which makes me thank it is claim/audience/issuer issue.  Any chance you could point me in correct direction to trouble shoot this further?  I am using the JwtRegisteredClaimNames.Sub claim per the few samples I have been able to find on the web and I am using my Azure Mobile App URL for audience and issuer - does all that sound correct?

**Comment by PaulAchess** [comment]
I noticed audience and issuer need a `/` at the end of the address to work, could this solve your issue?

**Comment by danbridgellc** [comment]
Thank you very much Paul - that was it!  added trailing / and it is working now.

**Comment by PaulAchess** [comment]
Glad I could help :+1:

**Comment by gaambo** [comment]
@PaulARoy - thanks for the tip with the trailing "/" - this solved my problem with debugging authentication locally. maybe this could be added in the documentation (https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#how-to-debug-and-troubleshoot-the-net-server-sdk)

**Comment by PaulARoy** [comment]
Perfect :)

I would be relevant yes.

**Comment by messvk** [comment]
Hi,

After reading through this, I still don't understand this:

How do you match provides ID when you are doing verification on Mobile devices (Windows, Xamarin.ios) as methods that are available on .net that are mentioned here are not available on mobile devices and we are still getting only SID that does not match what we already have in database.

We were using uniqueID from providers to identify our users in SQL database and it worked like charm on MobileServices. Now we want to migrate and have problem how our apps get to data stored in database.

I am unable to find anything about this and its major problem.

**Comment by phvannor** [comment]
@messvk the user object on the client SDKs will only have the SID populated in it now.  If you need to get additional information about the user you can either:
 - Call a custom API / table API that will get the additional information for you from the server (and use the above logic) post login.
- Use a client directed auth patten (get the id from fb/etc directly, and then pass the auth token to login to the app service app)

**Comment by messvk** [comment]
@phvannor 

1. I am not sure if i follow, can i send SID to custom API hat will get from sid user ID through methods on top? Or we need to somehow login on server side instead client side?
2. what do you mean by ◦Use a client directed auth patten?  Do you mean implement it directly through providers API instead of Azure? 

Whole point is to avoid updating client apps, because each update takes 2 weeks to certificate and its pain in the a** changing stuff like that in production environment without causing any disturbance in service and not mentioning cost of additional work that needs to be spend...

**Comment by phvannor** [comment]
One you are authenticated on the client (via client.login, etc) any request you make to you mobile app (or service) will have a X-ZUMO-AUTH header.  That header will auto populate the user object mentioned above, so you can just stand up a custom API, hit it, and use the above code, no other actions should ne needed.

Option 2, is more invasive and yeah, would be using the provider's APIs directly.  The calling the login+token method on the client.

I agree on having to make client changes in a pain, there are a handful of client-server contract breaking changes in the service to apps migration that should be called out in the migrate docs and if not, need to be. (@mahender can you look?)

Is your SQL filtering happening locally on the device against a local SQL db, or on the server?  If the latter, there are additional options here.  Your table script can be the one adding the filter based on the logged in user, and avoid having the client care.

**Comment by messvk** [comment]
@phvannor 
I understand the first part now, thank you.

Unfortunately its not that simple with us, as we are are providing heavily encrypted service with local encrypted database, asymetric encryption while communicating and than azure SQL, also encrypted where we have users and data.

problem is, that we are using this ID as part of generated security and communication, so we would have to change some of logic and it will add another unnecessary step, in order to provide access to locally stored data and communication with server, again cant be done without changing client apps... 

Currently old mobile service that was migrated works as before, but we would like to use new features in full someday, so for me it would be great if we got at least info, if those data will be some day available in client or we have to do all this work ourselves. 
We were very early adopters of azure, and spend lot of money and effort in building our service around it (that could be done on SAP HANA instead), and this feels like backstabbing changing crucial part of service in this radical way.

**Comment by phvannor** [comment]
@mattchenderson can you comment on plans re: above?

**Comment by JanCB** [comment]
Hi,

I have the same question as @renzska with two different Id for same user, ASP.NET 5 Web App and xamarin.iOS app 

Setup:
Azure WebApp ASP.NET 5 with API Controllers
Xamarin iOS App with Microsoft.WindowsAzure.Mobile.Client Nuget
Azure B2C AAD

When the user has authenticated from Web App I get the objectId: 

var userClaim = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;

While from Mobile App there is no objectIdentifier, only nameidentifier

var mobileClaim = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/nameidentifier").Value;

The id's are not the same while the user is the same in AAD, for know I need to store two id's for a user in my DB in order to identify the user. 

How can I retrieve the same id and which Id is the correct to use ?

**Comment by adrianhall** [comment]
Closing this issue as the original issue has been answered.  If anyone on the thread has additional issues (e.g. @JanCB ), then please post another question.  Thanks,

**Comment by som-nitjsr** [comment]
I have UWP app backend is azure mobile app service. I have configured azure b2c as authnetication. from last six month it is working fine.
on my client  side  i am using  DefaultManager.CurrentClient.CurrentUser.UserId which give me userid **{sid:value}** format.
on server side  this code was also giving **{sid:value}** and provider was **aad**
 var identity = User as ClaimsPrincipal;
            var userClaim = identity?.Claims.FirstOrDefault(b => b.Type == ClaimTypes.NameIdentifier);
           
Now from yesterday it is giving directly from b2c.
when i send the same request to local code it works as expected. but if i  debug uisng attcahing to azure mobile app. i am getting the same different value.
