### ISSUE TITLE
401 Unauthorized with users from providers (users authenticated earlier / expiration mechanism broken?)

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-apps-net-server#42]
Hi,

I'm having a lot of troubles right now with the provider authentication. We pushed into production the application on Monday, and we have had more than a thousand `401 - Unauthorized` responses.

We also have a lot of sync on error with `CancelledByAuthenticationError` (which comes from the same problem).

On production, we are using
* Client: WindowsAzure.MobileServices **2.0.0-beta-3**
* Server: Microsoft.Azure.Mobile.Server.xxx **0.3.36.0**

Diagnosis:
* These people were able to log-in with their provider: we have their data, they were fetched from the graph API so this was working at some point, for all users.
* This is happening for all the providers we support (Facebook, Twitter, Google)
* My custom auth seems not to be affected by this problem (I handle reconnection for expired tokens)

The X-ZUMO-AUTH header is correctly formatted, with `iss` and `aud` pointing to `https://mywebsite.azurewebsites.net/`

However, what's weird is that their token seems to be outdated, I have here a user with a token that has a `exp` at 1448964001 (01/12/2015 - 11:00:01), while the request was made at 01/12/2015 - 15:41:03.

Regarding auth, I'm storing the token and id like before in a vault on client-side, and putting it back like this:
```
MobileServiceUser msu = new MobileServiceUser(id);
msu.MobileServiceAuthenticationToken = token;
_mobileServiceClient.CurrentUser = msu;
```
Which is done like said here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-windows-store-dotnet-get-started-users/

Is the token mechanism broken / changed ? It's a huge regression for us, that is currently breaking all sync for users with provider authentication.

Please help, I'm really struggling with this right now :-(

**Comment by renzska** [comment]
I've been experiencing the a similar issue where the tokens are experiencing within an hour. This is causing all users to have to re-authenticate every hour. I've been using: http://www.epochconverter.com/ to compare the exp and nbf claim values from the "(this.User as ClaimsPrincipal).Claims".

@PaulAchess Is the "Token Store" enabled in your App/Auth settings? I'm curious what this does as it has not description on the Azure Portal page.

**Comment by PaulAchess** [comment]
Thanks, I feel a bit less lonely, I thought my custom auth was causing all this.

I'm not looking on server-side, I'm only seing the request from a log report with the zumo header.
http://jwt.io/ allows me to get the informations from the header, and I'm using http://www.timestamp.pro/ for timestamps.

The Token Store is **enabled**. Do you think I should try to disable it ?

Have you found a workaround ? Re-authenticating users every hour is not really an option for me…
Currently this is just blocking synchronization for me, but this will become a serious issue when they loose their data, as the forced disconnection purges the data…

**Comment by renzska** [comment]
If using mobile, I think we have to keep it enabled as per this post: https://azure.microsoft.com/en-us/blog/announcing-app-service-authentication-authorization/

I have not found a workaround as of yet.

> "Token Store
One other option you’ll note in the portal is the ability to enable or disable a token store. This feature allows underlying provider tokens to be stored in your application, accessible only when in the context of the associated user. This option is currently on by default and is required for mobile scenarios.

> In order to retrieve additional user information as well as any tokens required for graph calls, simply issue a GET to the /.auth/me endpoint on your site. If the request includes a valid session cookie or session token, information about the current user will be returned. The Mobile Apps server SDKs provide a GetAppServiceIdentityAsync() method to easily consume this API."

**Comment by mattchenderson** [comment]
The tokens that App Service issues are scoped to the lifetime of the backing provider token. So if you're seeing one hour, that would be because the token given to us by, say, Facebook, is scoped to an hour. There used to be a constant value applied for the social providers in Mobile Services. The provider-lifetime change was introduced with the App Service preview via the gateway, but now is a part of Authentication/Authorization.

So you would have always had the 401 issues, but now they're more frequent. The recommended flow is to catch 401s using something like delegating handlers, and if needed prompt the user for authentication again. Obviously we don't want users getting lots of login prompts, and ideally we'd leverage the refresh features many of the providers surface. However, we currently have an issue with this if you're using the "server flow" where Mobile Apps handles the login (e.g. LoginAsync("facebook");). We're working on a solution there, but I don't really have an ETA. If you are using a provider SDK to log in, these generally have refresh flows built-in, so you could silently extend the token lifetime without the user knowing. Those flows are supported in Mobile Apps today.

So if the provider SDKs exist for your platform, one option to fixing this in the short term is to switch to the "client flows" (LoginAsync("facebook", token);). If that's not achievable, then you could use custom authentication support to specify a token lifetime there, but I say that with the massive caveat that you are technically violating the security model set by the provider. I would say your best option is to use the client flow or wait on the refresh support.

The token store is required for now, and I apologize that the documentation there is poor. Basically this is where we store the backing token, available via the IPrincipal.GetAppServiceIdentityAsync() method. It's currently tied up in the token issuance pipeline, which is why it is presently required for mobile cases. I'm hoping to make it optional in the future.

**Comment by PaulAchess** [comment]
And that answer makes perfect sense and explains really well what is happening. I thank you a lot for this. I indeed saw a few 401 before but I never knew what was happening, as this was pretty rare.

**Comment by renzska** [comment]
For Facebook, I found the following from here: https://developers.facebook.com/docs/facebook-login/access-tokens

This tells how to extend the token:
https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

Is it possible for the azure mobile service to do this without us having to write additional code?

> Short-Term Tokens and Long-Term Tokens

> User access tokens come in two forms: short-lived tokens and long-lived tokens. Short-lived tokens usually have a lifetime of about an hour or two, while long-lived tokens usually have a lifetime of about 60 days. You should not depend on these lifetimes remaining the same - the lifetime may change without warning or expire early. See more under handling errors.

> Access tokens generated via web login are short-lived tokens, but you can convert them to long-lived tokens by making a server-side API call along with your app secret.

**Comment by renzska** [comment]
@PaulAchess I used this article for the 401 DelegateHandler mentioned modifying it a to meet my needs and now when my users get a 401, calling the LoginAsync in the example popups the login screen temporarily and dismisses it, refreshing with a new token without any user interaction needed. The window popup is not friendly, but it works around the 401 issue until something better comes along: http://blogs.msdn.com/b/carlosfigueira/archive/2014/03/13/caching-and-handling-expired-tokens-in-azure-mobile-services-managed-sdk.aspx

**Comment by PaulAchess** [comment]
That's indeed what I've done for the moment — try to get the user, get 401, prompt Login, get the user again.

As you said, not really friendly but it does the work. Thanks for sharing this :)

**Comment by brettsam** [comment]
@cgillum has written a [great blog post](http://cgillum.tech/2016/03/07/app-service-token-store/) documenting the token store. It explains how to use the new App Service Authentication feature for refreshing tokens (see the **Refreshing Tokens** section). There is a specific code sample there for Mobile Apps.
